# Generated by Django 5.0.4 on 2024-08-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitersite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccancy',
            name='id',
        ),
        migrations.AlterField(
            model_name='vaccancy',
            name='vaccancyid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
