# Generated by Django 5.0.4 on 2024-08-19 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitersite', '0003_alter_vaccancy_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicationid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cv', models.ImageField(blank=True, upload_to='static/cvs')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaccancy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recruitersite.vaccancy')),
            ],
        ),
    ]
