# Generated by Django 5.0.4 on 2024-08-21 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitersite', '0004_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('jobs', models.IntegerField(blank=True, max_length=5)),
                ('recruitment', models.IntegerField(blank=True, max_length=500)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
