# Generated by Django 5.0.4 on 2024-08-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitersite', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='jobs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recruitment',
            field=models.IntegerField(blank=True),
        ),
    ]
