# Generated by Django 5.0.4 on 2024-08-22 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitersite', '0006_alter_comment_jobs_alter_comment_recruitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('testimonialid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('testimony', models.CharField(blank=True, max_length=500)),
                ('date_posted', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
